<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h2>Login </h2>
    <?php echo $this->tag->form(''); ?>
    <p class="row">
        <label for="email" class='label'>Email</label>
        <?php echo $this->tag->textField(['email', 'class' => 'form-control col-12']) ?>
    </p>
    <p class="row">
        <label for="email" class='label'>Password</label>
        <?php echo $this->tag->textField(['password', 'class' => 'form-control col-12']) ?>
    </p>
    <p class="row">
        <label for="email" class='label'>Remember Me</label>
        <?php echo $this->tag->checkField(['Remember', 'class' => 'form-check-input']) ?>
    </p>
    <p>
        <?php echo $this->tag->submitButton("Login"); ?>
    </p>
    <?php echo $this->tag->endForm(); ?>
</body>

</html>