<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <header>
        <div class="row header mb-5">
            <div class="col-2">LOGO</div>
            <div class="col-2">Cart</div>
            <div class="col-2"><a href="http://localhost:8080/login">Login</a></div>
            <div class="col-2"><a href="http://localhost:8080/signup">Signup</a></div>
            <div class="col-2"><a href="http://localhost:8080/login/signout">Singout</a></div>
        </div>
    </header>
    <main>
        <div class="card" style="width: 18rem;">
            <img src="..." class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">Card title</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <a href="#" class="btn btn-primary">Add To store</a>
            </div>
        </div>
    </main>
</body>

</html>