<body class='text-center'>
    <h2 class='row mb-5'>Sign up</h2>

    <?php echo $this->tag->form(["signup/register", 'class' => 'form justify-content ']); ?>
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <p>
                <label for="username">Username</label>
                <?php echo $this->tag->textField(["username", 'class' => 'form-control']); ?>
            </p>

            <p>
                <label for="username">first name</label>
                <?php echo $this->tag->textField(["firstname", 'class' => 'form-control']); ?>
            </p>

            <p>
                <label for="username">first name</label>
                <?php echo $this->tag->textField(["lastname", 'class' => 'form-control']); ?>
            </p>

            <p>
                <label for="email">E-Mail</label>
                <?php echo $this->tag->textField(["email", 'class' => 'form-control']); ?>
            </p>
            <p>
                <label for="email">Password</label>
                <?php echo $this->tag->textField(["password", 'class' => 'form-control']); ?>
            </p>
            <p>
                <label for="email">Alredy User ?</label>
                <?php echo $this->tag->linkTo("login/", "Login"); ?>
            </p>
            <p>
                <?php echo $this->tag->submitButton(["Register", 'class' => 'btn btn-primary']); ?>
            </p>

        </div>
        <div class="col-3"></div>
    </div>
    </form>
</body>