<?php
header("Cache-Control: no cache");
?>
<!doctype html>
<html lang="en">

<head>
  <meta content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" name="viewport" />
  <meta name="viewport" content="width=device-width" />
  <link rel="stylesheet" href="../style.css" />
  <link rel="stylesheet" href="../node_modules/bootstrap/dist/css/bootstrap.min.css" />

  <script src="./node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
  <!-- Custom CSS -->
  <link rel="stylesheet" href="../assests/css/owl.carousel.css">
  <link rel="stylesheet" href="../style.css">
  <link rel="stylesheet" href="../assests/css/responsive.css">

  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>

</head>

<body class="bg-light">
  <header class='container p-0 mt-2'>

    <div class="row">
      <div class="col-12">
        <a class='border-0 btn bg-dark text-light w-100 pt-2 pb-2' href='../index.php'>Back to Store</a>
      </div>
    </div>
  </header>
  <div class="container">

    <main>
      <div class="py-5 text-center">
        <h2>Checkout form</h2>
      </div>
      <div class='row g-5 h1' id='orderCompleted'>
        Your order has been placed
      </div>
      <div class="row g-5" id="checkout">

        <div class="col-md-5 col-lg-4 order-md-last">
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-primary">Your cart</span>
            <span class="badge bg-primary rounded-pill"><?php echo count($cart['cart']) ?></span>
          </h4>
          <?php
          $html = "<ul class='list-group mb-3'>";
          $total = 0;
          foreach ($cart['cart'] as $key => $value) {
            $total += $value['sale_price'] * $value['quantity'];
            $html .= "<li class='list-group-item d-flex justify-content-between lh-sm'>
                      <div>
                        <h6 class='my-0'>$value[product_name]</h6>
                        <small class='text-muted'>Total Quantity : $value[quantity]</small><br>
                        <small class='text-muted'>$" .
              $value['sale_price'] * $value['quantity'] .
              "</small>
                        </div>
                      <span class='text-muted'>$$value[sale_price]</span>
                    </li>";
          }
          $html .= "
                    <li class='list-group-item d-flex justify-content-between'>
                      <span>Total (USD)</span>
                      <strong>$$total</strong>
                    </li>
                  </ul>";
          echo $html;
          ?>

        </div>
        <div class="col-md-7 col-lg-8 form">
          <h4 class="mb-3">Billing address</h4>
          <form action="http://localhost:8080/order/index" method="post" >
            <div class="row g-3">

              <div class="col-sm-6">
                <label for="firstName" class="form-label">First name</label>
                <?php if (isset($user)) {
                  echo "<input type='hidden' class='form-control' name ='user_id' ' value='$user[user_id]'  placeholder='' >";
                  echo "<input type='text' class='form-control' name='firstname' value=" . $user['firstname'] . " placeholder='' disabled>";
                } else {
                  echo "<input type='text' class='form-control' name='firstname' value='' placeholder='' >";
                }
                ?>
                <?php if (isset($cart)) {
                  echo "<input type='hidden' class='form-control' name='quantity' value=" . count($cart['cart']) . "  placeholder='' >";
                 
                }
                ?>
              </div>

              <div class="col-sm-6">
                <label for="lastname" class="form-label">Last name</label>
                <?php if (isset($user) == true) {
                  echo "<input type='text' class='form-control' name='lastname' value=" . $user['lastname'] . " placeholder='' disabled>";
                  echo "<input type='hidden' class='form-control' name='total' value=" . $total . "  placeholder='' >";
                } else {
                  echo "<input type='text' class='form-control' name='lastname' value='' placeholder='' >";
                }
                ?>
              </div>

              <div class="col-12">
                <label for="email" class="form-label">Email </label>
                <?php if (isset($user) == true) {
                  echo "<input type='email' class='form-control' name='email'  value=" . $user['email'] . " placeholder='you@example.com' disabled >";
                } else {
                  echo "<input type='email' class='form-control' name='email'  value='' placeholder='you@example.com'  >";
                }
                ?>
              </div>

              <div class="col-12">
                <label for="address" class="form-label">Address</label>
                <input type="text" class="form-control" name="address" value="<?php

                                                                            if (isset($user)) {
                                                                              echo $user['address'];
                                                                            }


                                                                            ?>" placeholder="1234 Main St">

              </div>


              <div class="col-md-5">
                <label for="country" class="form-label">Country</label>
                <input type="text" class="form-control" name="country" value="<?php
                                                                            if (isset($user)) {
                                                                              echo $user['country'];
                                                                            }
                                                                            ?>" placeholder="">


              </div>

              <div class="col-md-4">
                <label for="state" class="form-label">State</label>
                <input type="text" class="form-control" name="state" value="<?php
                                                                          if (isset($user)) {
                                                                            echo $user['state'];
                                                                          }
                                                                          ?>" placeholder="">

              </div>

              <div class="col-md-3">
                <label for="zip" class="form-label">Pincode</label>
                <input type="text" class="form-control" name="pincode" value="<?php
                                                                            if (isset($user)) {
                                                                              echo $user['pincode'];
                                                                            }
                                                                            ?>" placeholder="">
              </div>
            </div>
            <hr class="my-4">
            <button class="w-100 btn btn-primary btn-lg" name='submit' type="submit">Place Order</button>
          </form>
        </div>
      </div>
    </main>

    <footer class="my-5 pt-5 text-muted text-center text-small">
      <p class="mb-1">&copy; 2017–2021 Company Name</p>
      <ul class="list-inline">
        <li class="list-inline-item"><a href="#">Privacy</a></li>
        <li class="list-inline-item"><a href="#">Terms</a></li>
        <li class="list-inline-item"><a href="#">Support</a></li>
      </ul>
    </footer>
  </div>
  <script src="../node_modules/bootstrap/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
  <script src="./assets/js/form-validation.js"></script>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="../assests/js/checkout.js" rel="text/javascript"></script>

</html>