<?php
header("Cache-Control: no cache");
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body class="container">
    <?php if (isset($msg)) {
        echo '<h1 class="alert alert-success border mt-5 ">' . $msg . '</h1>';
        echo $this->tag->linkTo(['index','Back to Store','class' =>'btn btn-primary']);
    } ?>
</body>

</html>